### ISSUE TITLE
Cant get it working

### ISSUE THREAD

**Issue by life-coder** [PeterZander/i2p-cs#1]
So, this is awesome work! I congratulate you. I want to help you with the development, but I run into some issues when running it, in RouletteSelection.cs in I2PCore.dll on line 58(MaxFit = Wheel.Max(sp => sp.Fit);) It throws an exception: System.InvalidOperationException: 'Sequence contains no elements' which I cant seem to fix... If you could help me?

Thanks and again, awesome work!

**Comment by PeterZander** [comment]
You need to seed the database with routers as bootstrapping is not implemented.

Take all the subdirectories from  
C:\Users\ [username]\AppData\Roaming\i2pd\netDb
if you have a i2pd installation and paste to
C:\Users\ [username]\AppData\Roaming\I2Pz\netDb
(or what the startup says is the netdb dir)

**Comment by life-coder** [comment]
Stupid, should've thought of that, thanks :)
