### ISSUE TITLE
Pay to finish

### ISSUE THREAD

**Issue by matthias-hoste** [PeterZander/i2p-cs#2]
Hi,

I really love your work on this. Would you accept payment to continue working on this? If so, how can I contact you?

Best regards

**Comment by PeterZander** [comment]
I suspect that this is no longer of interest. Closing.

**Comment by matthias-hoste** [comment]
Well it really depends. I'm still willing to sponsor this since I could really use it, but I'm also willing to help implement things/fix bugs etc
